### PR TITLE
Start testing against Python 3.12

### PR DESCRIPTION
**Pull request by sethmlarson**

### CODE REVIEW

**Comment by davisagli** [comment]
Alas, it doesn't look like test_trustme_cert_loaded_via_capath is stable yet (see 3.10 build)

**Comment by sethmlarson** [comment]
@davisagli This isn't yet rebased, let me try after that.

**Comment by sethmlarson** [comment]
@davisagli Oh it is rebased, didn't notice!

**Review by davisagli — APPROVED** [review]

**Review by davisagli — APPROVED** [review]

**Comment by davisagli** [comment]
@sethmlarson It says it can't be merged because the base branch requires all commits to be signed. I rebased using the button in the web UI, and I guess that created an unsigned commit. Might need to rebase again or temporarily remove the restriction.

**Comment by sethmlarson** [comment]
@davisagli It's all good, I can squash merge and it'll sign I think?

**Pull request merged**
