### PR TITLE
Verify leaf cert using wincrypt APIs

### PR DESCRIPTION
**Pull request by davisagli**
This fixes https://github.com/sethmlarson/truststore/issues/8 by implementing cert verification using the CryptoAPI in Windows.

### CODE REVIEW

**Comment by sethmlarson** [comment]
Wow! This is awesome!! 🤩 I have a WIP implementation too that adds intermediates to a certstore. Let's get this one merged first then add more?

**Comment by davisagli** [comment]
I think we need an additional test to confirm we're paying attention to intermediates from the server. But I'm fine with either merging this as is or waiting.

**Comment by davisagli** [comment]
Now it's passing intermediate certs in an in-memory cert store. I verified these are used for verification by temporarily passing the CERT_CHAIN_DISABLE_AIA flag to CertGetCertificateChain, so that Windows would not automatically fetch the intermediate via the [Authority Information Access](https://datatracker.ietf.org/doc/html/rfc5280#section-4.2.2.1) info embedded in the leaf cert. I'm not quite sure how to add a real test that intermediates from the server are used; I think we would need to find a server that presents a cert issued by an intermediate but lacking AIA info.

**Comment by davisagli** [comment]
https://untrusted-root.badssl.com/ has a cert with no AIA extension, so maybe we can use it for a combined test that verification uses the cert chain from the server and that trust anchors manually added using load_verify_locations are trusted, once #9 is implemented.

**Comment by sethmlarson** [comment]
@davisagli  nice, I'm unaware of a particular server that's doing that. Maybe we can create an issue for verifying intermediates after we implement custom certificates and can then verify against trustme-generated certs?

**Review by sethmlarson — APPROVED** [review]
This looks great to me, thank you for all the time you've put into this.

**Comment by sethmlarson** [comment]
@davisagli Can I send you a collaborator invite for this project btw?

**Comment by davisagli** [comment]
> Can I send you a collaborator invite for this project btw?

@sethmlarson sure!

**Pull request merged**
