### PR TITLE
Add assertations for error message variation, keywords in load_verify_locations()

### PR DESCRIPTION
**Pull request by sethmlarson**

### CODE REVIEW

**Comment by davisagli** [comment]
@sethmlarson Hmm, tough to keep these tests working, eh?

The Windows 3.10 failure is one we've seen intermittently and haven't found the root cause for yet.

The Windows 3.11 failure looks timing-related. Maybe worth a retry?

We should also probably set up a nightly CI run.

**Comment by sethmlarson** [comment]
@davisagli Yeah this test suite is pretty flaky which is a shame, trying to figure out the capath one right now. Definitely might need some retries on ones depending on external services.

**Comment by sethmlarson** [comment]
@davisagli I think this is ready for a review now, the `os.listdir()` seems to make things work as expected. Maybe we were calling `load_verify_locations` before the symlink was showing up? Not sure.

**Review by davisagli — APPROVED** [review]
Makes sense; I was also wondering if it was a timing issue with the symlink creation.

**Pull request merged**
