### PR TITLE
Add integration tests for pip

### LINKED ISSUE #49: Add integration test using pip's --use-feature=truststore
Depends on https://github.com/pypa/pip/pull/11082

We should ensure we don't break any of pip's users trying to use our experimental feature flag `--use-feature=truststore`, at least for a basic installation from PyPI. It's tougher for us to simulate installing from corporate proxies/package indices but maybe we can do something with mkcert and warehouse?

### PR DESCRIPTION
**Pull request by sethmlarson**
Closes #49

### CODE REVIEW

**Review by davisagli — COMMENTED** [review]
Great!

Are you sure the tests are running using the truststore checkout and not with an installation of the released version? The test is explicitly pip installing truststore here: https://github.com/pypa/pip/pull/11082/files#diff-a5047544edabab77bcc833c6db13a484c0911014e9b2fd71c429c238aa106ab1R59 -- I guess that should find that the package installed from the checkout is already there and do nothing, but maybe worth double checking?

Should we put this in a separate github workflow that is scheduled to run periodically? That way if pip changes in a way that breaks truststore, we find out proactively rather than only when we push to truststore.

**Comment by sethmlarson** [comment]
@davisagli Thanks for the review, great ideas! I'll try pushing a broken commit and see that the integration tests fail.

**Comment by davisagli** [comment]
@sethmlarson oh no, it succeeded!

**Comment by sethmlarson** [comment]
Your hunch was spot-on, now to figure out how we can somehow circumvent pip installing us during their test suite... :thinking:

**Comment by davisagli** [comment]
Hmm, nox is going to make that difficult for us, isn't it. Maybe apply a patch to test_truststore.py in between checking out pip and running the tests, to make it install truststore from a relative path instead of from PyPI?

**Review by davisagli — APPROVED** [review]

**Comment by sethmlarson** [comment]
@davisagli Thanks for the fix, review, and merge!! 💪

**Pull request merged**
