### PR TITLE
Run CI on Python 3.11

### PR DESCRIPTION
**Pull request by adriangb**
Currently it is silently not running: https://github.com/sethmlarson/truststore/runs/6300836636?check_suite_focus=true#step:4:39

### CODE REVIEW

**Comment by davisagli** [comment]
I already did some work on this in #33, but I think it's blocked waiting for a new release of Cython to build new releases of some of our dependencies for Python 3.11

**Comment by adriangb** [comment]
Ah okay I missed that! Maybe explicitly skip this version or something for now? It was a tad confusing to see.

**Comment by davisagli** [comment]
> Maybe explicitly skip this version or something for now? It was a tad confusing to see.

Yeah, that's a fair request. I keep hoping it'll get fixed soon but since it's not, we should probably just take 3.11 out of the matrix for now.

**Comment by davisagli** [comment]
#54

**Pull request closed without merging**
