### PR TITLE
Test on Windows and macOS

### PR DESCRIPTION
**Pull request by sethmlarson**

### CODE REVIEW

**Comment by notatallshaw** [comment]
FYI, cffi needs to be installed from Github source for Python 3.13 until their next release, like in this PR: https://github.com/pypa/pip/pull/12620

**Comment by sethmlarson** [comment]
@notatallshaw Thanks for the link, I'll give that a try :)

**Comment by sethmlarson** [comment]
@davisagli I believe what's happening is that we're seeing one type (`bytes`) from `get_unverified_chain()` for `MemoryBIO` and another type (`_ssl.Certificate`) from `SSLSocket` which is why I added the `isinstance` check.

**Review by davisagli — APPROVED** [review]
@sethmlarson LGTM, but I wonder if that inconsistency should be reported upstream

**Comment by sethmlarson** [comment]
@davisagli Definitely, here's the upstream issue: https://github.com/python/cpython/issues/118658

**Pull request merged**
